-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.auditoria
(
    id serial NOT NULL,
    ticket_id integer NOT NULL,
    usuario_id integer NOT NULL,
    accion character varying(50) COLLATE pg_catalog."default" NOT NULL,
    detalle jsonb,
    fecha_hora timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT auditoria_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.contactos
(
    numero_telefono character varying(20) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default",
    sucursal character varying(100) COLLATE pg_catalog."default",
    creado_en timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    actualizado_en timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT contactos_pkey PRIMARY KEY (numero_telefono)
);

CREATE TABLE IF NOT EXISTS public.mensajes
(
    id serial NOT NULL,
    ticket_id integer NOT NULL,
    remitente character varying(10) COLLATE pg_catalog."default" NOT NULL,
    tecnico_id integer,
    contenido text COLLATE pg_catalog."default" NOT NULL,
    tipo character varying(20) COLLATE pg_catalog."default" DEFAULT 'texto'::character varying,
    url_adjunto character varying(255) COLLATE pg_catalog."default",
    whatsapp_message_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    enviado_en timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT mensajes_pkey PRIMARY KEY (id),
    CONSTRAINT mensajes_whatsapp_message_id_key UNIQUE (whatsapp_message_id)
);

CREATE TABLE IF NOT EXISTS public.tickets
(
    id serial NOT NULL,
    numero_cliente character varying(20) COLLATE pg_catalog."default" NOT NULL,
    estado character varying(20) COLLATE pg_catalog."default" NOT NULL,
    tecnico_asignado_id integer,
    solicitud_transferencia_tecnico_id integer,
    transferido boolean NOT NULL DEFAULT false,
    categoria character varying(50) COLLATE pg_catalog."default",
    creado_en timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    actualizado_en timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    cerrado_en timestamp without time zone,
    CONSTRAINT tickets_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.usuarios
(
    id serial NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "contraseña_hash" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    rol character varying(20) COLLATE pg_catalog."default" NOT NULL,
    creado_en timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    actualizado_en timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT usuarios_pkey PRIMARY KEY (id),
    CONSTRAINT usuarios_email_key UNIQUE (email)
);

ALTER TABLE IF EXISTS public.auditoria
    ADD CONSTRAINT auditoria_ticket_id_fkey FOREIGN KEY (ticket_id)
    REFERENCES public.tickets (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_auditoria_ticket_id
    ON public.auditoria(ticket_id);


ALTER TABLE IF EXISTS public.auditoria
    ADD CONSTRAINT auditoria_usuario_id_fkey FOREIGN KEY (usuario_id)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_auditoria_usuario_id
    ON public.auditoria(usuario_id);


ALTER TABLE IF EXISTS public.mensajes
    ADD CONSTRAINT mensajes_tecnico_id_fkey FOREIGN KEY (tecnico_id)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.mensajes
    ADD CONSTRAINT mensajes_ticket_id_fkey FOREIGN KEY (ticket_id)
    REFERENCES public.tickets (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_mensajes_ticket_id
    ON public.mensajes(ticket_id);


ALTER TABLE IF EXISTS public.tickets
    ADD CONSTRAINT tickets_numero_cliente_fkey FOREIGN KEY (numero_cliente)
    REFERENCES public.contactos (numero_telefono) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_tickets_numero_cliente
    ON public.tickets(numero_cliente);


ALTER TABLE IF EXISTS public.tickets
    ADD CONSTRAINT tickets_solicitud_transferencia_tecnico_id_fkey FOREIGN KEY (solicitud_transferencia_tecnico_id)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_tickets_solicitud_transferencia
    ON public.tickets(solicitud_transferencia_tecnico_id);


ALTER TABLE IF EXISTS public.tickets
    ADD CONSTRAINT tickets_tecnico_asignado_id_fkey FOREIGN KEY (tecnico_asignado_id)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_tickets_tecnico_asignado
    ON public.tickets(tecnico_asignado_id);

END;